[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"
  ignore = "git diff --quiet $CACHED_COMMIT HEAD -- public/ src/ netlify/ package.json netlify.toml && exit 1 || exit 0"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
